ALTER TABLE projects ALTER COLUMN workspace_id TYPE uuid USING workspace_id::uuid;
CREATE UNIQUE INDEX IF NOT EXISTS workspaces_id_owner_key ON workspaces (id, clerk_id);
CREATE UNIQUE INDEX IF NOT EXISTS projects_id_scope_key ON projects (id, workspace_id, clerk_id);
CREATE UNIQUE INDEX IF NOT EXISTS projects_id_owner_key ON projects (id, clerk_id);
ALTER TABLE projects ADD CONSTRAINT projects_workspace_owner_fk FOREIGN KEY (workspace_id, clerk_id) REFERENCES workspaces (id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE projects ADD CONSTRAINT projects_progress_range CHECK (progress BETWEEN 0 AND 100) NOT VALID;
ALTER TABLE skills ADD CONSTRAINT skills_progress_range CHECK (progress BETWEEN 0 AND 100) NOT VALID;
ALTER TABLE time_entries ADD CONSTRAINT time_entries_minutes_range CHECK (minutes BETWEEN 1 AND 1440) NOT VALID;
ALTER TABLE evidence ADD CONSTRAINT evidence_file_size_range CHECK (file_size IS NULL OR file_size BETWEEN 1 AND 2097152) NOT VALID;
ALTER TABLE findings ADD CONSTRAINT findings_workspace_owner_fk FOREIGN KEY (workspace_id, clerk_id) REFERENCES workspaces (id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE findings ADD CONSTRAINT findings_project_scope_fk FOREIGN KEY (project_id, workspace_id, clerk_id) REFERENCES projects (id, workspace_id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE evidence ADD CONSTRAINT evidence_workspace_owner_fk FOREIGN KEY (workspace_id, clerk_id) REFERENCES workspaces (id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE evidence ADD CONSTRAINT evidence_project_scope_fk FOREIGN KEY (project_id, workspace_id, clerk_id) REFERENCES projects (id, workspace_id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE reports ADD CONSTRAINT reports_workspace_owner_fk FOREIGN KEY (workspace_id, clerk_id) REFERENCES workspaces (id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE reports ADD CONSTRAINT reports_project_scope_fk FOREIGN KEY (project_id, workspace_id, clerk_id) REFERENCES projects (id, workspace_id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE notes ADD CONSTRAINT notes_workspace_owner_fk FOREIGN KEY (workspace_id, clerk_id) REFERENCES workspaces (id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE notes ADD CONSTRAINT notes_project_scope_fk FOREIGN KEY (project_id, workspace_id, clerk_id) REFERENCES projects (id, workspace_id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE time_entries ADD CONSTRAINT time_entries_workspace_owner_fk FOREIGN KEY (workspace_id, clerk_id) REFERENCES workspaces (id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE time_entries ADD CONSTRAINT time_entries_project_scope_fk FOREIGN KEY (project_id, workspace_id, clerk_id) REFERENCES projects (id, workspace_id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE activities ADD CONSTRAINT activities_workspace_owner_fk FOREIGN KEY (workspace_id, clerk_id) REFERENCES workspaces (id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE activities ADD CONSTRAINT activities_project_scope_fk FOREIGN KEY (project_id, workspace_id, clerk_id) REFERENCES projects (id, workspace_id, clerk_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE team_members ADD CONSTRAINT team_members_project_owner_fk FOREIGN KEY (project_id, clerk_id) REFERENCES projects (id, clerk_id) ON DELETE CASCADE NOT VALID;
