"use client";
import Link from "next/link";
import { useState } from "react";
import { Download, ExternalLink, Search } from "lucide-react";
import { Badge, DeleteButton, Empty } from "./ui";
import { deleteRecord } from "../actions";
export type CollectionRow={id:string;title:string;description:string;workspace:string;project:string;href:string;category:string;status:string;severity?:string;updated:string;sourceUrl?:string|null;fileName?:string|null};
export function Collection({kind,rows}:{kind:"finding"|"evidence"|"report";rows:CollectionRow[]}) {
  const [query,setQuery]=useState(""),[status,setStatus]=useState("All"),[workspace,setWorkspace]=useState("All");
  const filtered=rows.filter(r=>`${r.title} ${r.description} ${r.project} ${r.workspace} ${r.severity||""}`.toLowerCase().includes(query.toLowerCase())&&(status==="All"||r.status===status)&&(workspace==="All"||r.workspace===workspace));
  const [limit,setLimit]=useState(30);
  return <section className="board"><div className="board-title flex-wrap"><div><h2>All {kind==="evidence"?"evidence":`${kind}s`}</h2><p>{filtered.length} of {rows.length} records</p></div><Link className="button-secondary" href="/workspaces">Open a project to add {kind}</Link></div><div className="flex flex-wrap gap-3 border-b border-[#29323a] p-4"><label className="search-field min-w-[180px] flex-1"><Search size={15} aria-hidden="true"/><input className="field" aria-label={`Search ${kind}s`} value={query} placeholder={`Search ${kind==="evidence"?"evidence":`${kind}s`}…`} onChange={e=>{setQuery(e.target.value);setLimit(30);}}/></label><select className="field w-auto max-w-full" aria-label="Filter by workspace" value={workspace} onChange={e=>{setWorkspace(e.target.value);setLimit(30);}}><option value="All">All workspaces</option>{[...new Set(rows.map(r=>r.workspace))].map(w=><option key={w}>{w}</option>)}</select><select className="field w-auto" aria-label="Filter by status or type" value={status} onChange={e=>{setStatus(e.target.value);setLimit(30);}}><option value="All">{kind==="evidence"?"All types":"All statuses"}</option>{[...new Set(rows.map(r=>r.status))].map(s=><option key={s}>{s}</option>)}</select></div><div className="divide-y divide-[#29323a]">{filtered.slice(0,limit).map(r=><article className="item flex-wrap" key={r.id}><div className="item-main min-w-[150px]"><Link href={r.href} className="break-words text-sm font-semibold hover:text-[#bddbcc]">{r.title}</Link><p className="line-clamp-2 break-words">{r.description||r.category}</p><small>{r.workspace} · {r.project} · {new Date(r.updated).toLocaleDateString()}</small>{kind==="evidence"&&<div className="mt-3 flex flex-wrap gap-2">{r.fileName&&<a className="button-secondary" href={`/api/evidence/${r.id}/download`}><Download size={13}/>Download</a>}{r.sourceUrl&&<a className="button-secondary" href={r.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={13}/>Source</a>}</div>}</div><div className="flex items-center gap-2">{r.severity&&<Badge tone={r.severity}>{r.severity}</Badge>}<Badge tone={r.status}>{r.status}</Badge><DeleteButton name={r.title} action={()=>deleteRecord(kind,r.id)}/></div></article>)}</div>{!filtered.length&&<Empty>{rows.length?"No records match these filters.":`No ${kind==="evidence"?"evidence":`${kind}s`} yet. Open a project to get started.`}</Empty>}{filtered.length>limit&&<div className="p-4 text-center"><button className="button-secondary" onClick={()=>setLimit(limit+30)}>Show more</button></div>}</section>;
}

