"use client";
import {useState} from "react";
import Link from "next/link";
import {ArrowDownRight,ArrowUpRight,Check,FileText,FolderKanban,Plus} from "lucide-react";
import {Empty,Panel} from "./ui";
import {AIInsight} from "./ai-insight";
type Project={id:string;workspaceId:string;name:string;workspace:string;progress:number;status:string;dueDate:string|null};
type Finding={id:string;title:string;status:string;severity:string;workspaceId:string;projectId:string|null};
type Activity={id:string;message:string;createdAt:string};
export type DashboardData={projects:Project[];findings:Finding[];workspaceCount:number;evidenceCount:number;reportCount:number;finalReports:number;activity:Activity[];daily:{day:string;value:number}[];today:string};
export function Dashboard({data}:{data:DashboardData}){
  const [period,setPeriod]=useState(28),[filter,setFilter]=useState("Active");
  const active=data.projects.filter(p=>p.status!=="Complete"),open=data.findings.filter(f=>f.status!=="Resolved");
  const visible=data.projects.filter(p=>filter==="All"||(filter==="Active"?p.status!=="Complete":p.status==="Complete"));
  const levels=[{name:"Critical",color:"#ed7965"},{name:"High",color:"#efa56e"},{name:"Medium",color:"#d5c28b"},{name:"Low",color:"#82b9c2"},{name:"Informational",color:"#758491"}];
  const max=Math.max(1,...levels.map(s=>open.filter(f=>f.severity===s.name).length));
  const days=Array.from({length:period},(_,i)=>{const d=new Date(`${data.today}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-period+i+1);const day=d.toISOString().slice(0,10);return {day,value:data.daily.find(v=>v.day===day)?.value||0};});
  const activityMax=Math.max(1,...days.map(d=>d.value));
  return <div className="page dashboard-page"><header className="dashboard-header"><div><p className="eyebrow">Overview</p><h1>Good to see you.</h1><p>Review your active assessments and pick up where you left off.</p></div><Link href="/workspaces" className="button"><Plus size={14}/>New workspace</Link></header>
  <section className="metric-strip" aria-label="Research summary">{[{label:"ACTIVE PROJECTS",value:active.length,note:`${data.workspaceCount} workspaces`,href:"/workspaces"},{label:"OPEN FINDINGS",value:open.length,note:`${open.filter(f=>["Critical","High"].includes(f.severity)).length} high / critical`,href:"/findings"},{label:"EVIDENCE RECORDS",value:data.evidenceCount,note:"Captured & documented",href:"/evidence"},{label:"ASSESSMENT REPORTS",value:data.reportCount,note:`${data.finalReports} finalized`,href:"/reports"}].map((m,i)=><Link key={m.label} className="metric-cell" href={m.href}><div className="metric-label"><span>{m.label}</span><span>0{i+1}</span></div><div className="metric-value">{String(m.value).padStart(2,"0")}<ArrowUpRight size={18}/></div><p>{m.note}</p></Link>)}</section>
  <AIInsight request={{kind:"overview"}} />
  <div className="dashboard-grid"><div className="dashboard-main"><Panel title="On your desk" action={<div className="segmented">{["Active","Complete","All"].map(v=><button key={v} onClick={()=>setFilter(v)} aria-pressed={filter===v}>{v}</button>)}</div>}><div className="project-list-head"><span>PROJECT / WORKSPACE</span><span>PROGRESS</span></div>{visible.slice(0,5).map((p,i)=><Link className="desk-project" href={`/workspaces/${p.workspaceId}/projects/${p.id}`} key={p.id}><span className="project-seal"><FolderKanban size={19} strokeWidth={1.4}/><small>{String(i+1).padStart(2,"0")}</small></span><div className="desk-title"><h3>{p.name}</h3><p>{p.workspace}{p.dueDate&&` / Due ${p.dueDate}`}</p></div><div className="desk-progress"><span>{p.progress}%</span><div><i style={{width:`${p.progress}%`}}/></div></div><ArrowUpRight size={15}/></Link>)}{!visible.length&&<Empty>{data.projects.length?"No projects in this view.":"Your desk is clear. Create a workspace to start your first assessment."}</Empty>}<Link href="/workspaces" className="panel-bottom-link">View all workspaces<ArrowUpRight size={14}/></Link></Panel>
  <Panel title="Research rhythm" action={<div className="segmented">{[7,28].map(v=><button key={v} aria-pressed={period===v} onClick={()=>setPeriod(v)}>{v} days</button>)}</div>}><div className="rhythm-summary"><strong>{days.reduce((sum,d)=>sum+d.value,0)}</strong><span>recorded actions<br/>over the last {period} days</span><span className="rhythm-legend"><i/>RESEARCH ACTIVITY</span></div><div className="activity-chart" role="img" aria-label={`${days.reduce((s,d)=>s+d.value,0)} research actions in the last ${period} days`}>{days.map(d=><div className="activity-column" key={d.day} tabIndex={0} aria-label={`${d.day}: ${d.value} actions`}><div className="activity-bar" style={{height:`${d.value?Math.max(8,d.value/activityMax*100):2}%`}} data-empty={!d.value}/><span className="activity-tooltip">{d.day}<br/>{d.value} actions</span></div>)}</div><div className="chart-axis"><span>{days[0].day}</span><span>{data.today}</span></div></Panel></div>
  <div className="dashboard-side"><Panel title="Risk distribution" action={<Link href="/findings" aria-label="Open findings" className="icon-button"><ArrowUpRight size={14}/></Link>}><div className="risk-total"><strong>{String(open.length).padStart(2,"0")}</strong><span>open findings<br/>by severity</span><ArrowDownRight size={28}/></div><div className="risk-bars">{levels.map(s=>{const value=open.filter(f=>f.severity===s.name).length;return <div className="risk-row" key={s.name}><span>{s.name}</span><div><i style={{width:`${value/max*100}%`,background:s.color}}/></div><b>{value}</b></div>;})}</div><p className="instrument-note">{open.length?"Prioritize the issues with the greatest impact.":"No open findings. Your next observation starts in a project."}</p></Panel><Panel title="Latest entries">{data.activity.length?<div className="activity-timeline">{data.activity.slice(0,5).map(a=><div key={a.id}><i/><p>{a.message}<span>{new Date(a.createdAt).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</span></p></div>)}</div>:<div className="first-entry"><FileText size={24} strokeWidth={1}/><p>A clean page.<br/>Your research trail starts here.</p><Link href="/workspaces">Start documenting<ArrowUpRight size={13}/></Link></div>}</Panel></div></div>
  {!data.findings.length&&<section className="onboarding-strip"><span className="onboarding-icon"><Check size={20}/></span><div><strong>Build the habit. Keep the evidence.</strong><p>Open your project, record a finding, attach the proof, and turn it into a report.</p></div><Link href={data.projects[0]?`/workspaces/${data.projects[0].workspaceId}/projects/${data.projects[0].id}`:"/workspaces"} className="text-action">Continue your research<ArrowUpRight size={14}/></Link></section>}</div>;
}
