"use client";
import { createEvidence, createFinding, createNote, editEvidence, editFinding, editNote } from "../actions";
import { categories, evidenceKinds, findingStatuses, severities } from "../lib/validation";
import { ActionForm, Field, HiddenScope } from "./ui";
export type Finding = { id:string;title:string;category:string;severity:string;status:string;description:string|null };
export type Evidence = { id:string;name:string;category:string;kind:string;description:string|null;sourceUrl:string|null;fileName:string|null;fileSize:number|null;sha256:string|null };
export type Note = {id:string;title:string;content:string;createdAt:string};
type Scope = {workspaceId:string;projectId:string;onSaved:()=>void};
export function FindingForm({workspaceId,projectId,onSaved,record}:{record?:Finding}&Scope) { return <ActionForm action={record?editFinding.bind(null,record.id):createFinding} label={record?"Save finding":"Create finding"} onSuccess={onSaved}><HiddenScope workspaceId={workspaceId} projectId={projectId}/><Field label="Title"><input name="title" required maxLength={200} autoFocus className="field" defaultValue={record?.title} placeholder="What did you discover?"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Category"><select className="field" name="category" defaultValue={record?.category||"Vulnerability"}>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Severity"><select className="field" name="severity" defaultValue={record?.severity||"Medium"}>{severities.map(c=><option key={c}>{c}</option>)}</select></Field></div>{record&&<Field label="Status"><select className="field" name="status" defaultValue={record.status}>{findingStatuses.map(s=><option key={s}>{s}</option>)}</select></Field>}<Field label="Description, impact & remediation"><textarea name="description" maxLength={30000} rows={7} className="field" defaultValue={record?.description||""} placeholder="Affected targets, reproduction steps, impact, and recommended next steps."/></Field></ActionForm>; }
export function EvidenceForm({workspaceId,projectId,onSaved,record}:{record?:Evidence}&Scope) { return <ActionForm action={record?editEvidence.bind(null,record.id):createEvidence} label="Save evidence" onSuccess={onSaved}><HiddenScope workspaceId={workspaceId} projectId={projectId}/><Field label="Evidence name"><input required name="name" maxLength={200} autoFocus className="field" defaultValue={record?.name}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Category"><select className="field" name="category" defaultValue={record?.category||"Supporting evidence"}>{["Supporting evidence",...categories].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Artifact type"><select className="field" name="kind" defaultValue={record?.kind||"Document"}>{evidenceKinds.map(c=><option key={c}>{c}</option>)}</select></Field></div><Field label="Source URL (optional unless type is Link)"><input type="url" name="sourceUrl" maxLength={2000} className="field" defaultValue={record?.sourceUrl||""} placeholder="https://…"/></Field><Field label={record?.fileName?`Replace attachment (${record.fileName})` : "Attachment (optional)"}><input name="file" type="file" className="field file:mr-3 file:rounded file:border-0 file:bg-[#2b3a33] file:px-3 file:py-1 file:text-[#c9e0d6]"/><span className="mt-2 block text-xs font-normal text-[#89969e]">Up to 2 MB. Private download with a SHA-256 integrity hash. Use a source link for larger files.</span></Field><Field label="Source & context"><textarea name="description" maxLength={30000} rows={5} className="field" defaultValue={record?.description||""} placeholder="What does this artifact demonstrate?"/></Field></ActionForm>; }
export function NoteForm({workspaceId,projectId,onSaved,record}:{record?:Note}&Scope) { return <ActionForm action={record?editNote.bind(null,record.id):createNote} label="Save note" onSuccess={onSaved}><HiddenScope workspaceId={workspaceId} projectId={projectId}/><Field label="Title"><input name="title" required maxLength={200} autoFocus className="field" defaultValue={record?.title}/></Field><Field label="Research note"><textarea name="content" required maxLength={30000} rows={10} className="field font-mono" defaultValue={record?.content} placeholder="Commands, reasoning, and follow-up questions…"/></Field></ActionForm>; }
